routes/web.php
<?php

use App\Http\Controllers\AreaController;
use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MarkController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\StatuController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect()->route('login');
});

Auth::routes();



Route::middleware(['auth'])->group(function () {
  Route::get('/home', [HomeController::class, 'index'])->name('home');
  Route::get('users', [UserController::class, 'index'])->name('users.index');
  Route::get('profile', [ProfileController::class, 'show'])->name('profile.show');
  Route::put('profile', [ProfileController::class, 'update'])->name('profile.update');
  Route::resource('areas', AreaController::class);
  Route::resource('categories', CategoryController::class);
  Route::resource('marks', MarkController::class);
  Route::resource('status', StatuController::class);
  Route::resource('products', ProductController::class);
});

app/Models/Statu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Statu extends Model
{
  use HasFactory;
  protected $fillable = ['id', 'name'];
  public function products(): HasMany
  {
    return $this->hasMany(Product::class);
  }
}

app/Http/Controllers/StatuController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Statu\AddRequest;
use App\Http\Requests\Statu\UpdateRequest;
use App\Models\Statu;
use Illuminate\Http\Request;

class StatuController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {

    $status = Statu::all();
    return view('admin.status.index', compact('status'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    //
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(AddRequest $request)
  {
    Statu::create($request->all());
    return redirect()->route('status.index')->with(['message' => 'Agregado', 'color' => 'success']);
  }

  /**
   * Display the specified resource.
   *
   * @param  \App\Models\Statu  $statu
   * @return \Illuminate\Http\Response
   */
  public function show(Statu $statu)
  {
    //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  \App\Models\Statu  $statu
   * @return \Illuminate\Http\Response
   */
  public function edit(Statu $statu, $id)
  {
    $statu = Statu::find($id);
    return view('admin.status.edit', compact('statu'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  \App\Models\Statu  $statu
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    $messages =
      [
        'name.required' => 'El nombre debe ser requerido',
        'name.unique' => 'El nombre ya existe '
      ];
    $request->validate([
      'name' => 'required|unique:status,name,' . $id,

    ], $messages);
    Statu::where('id', $id)->update($request->only('name'));
    return redirect()->route('status.index')->with(['message' => 'Editado', 'color' => 'success']);
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  \App\Models\Statu  $statu
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
    $color = "danger";
    $message = "No se pudo eliminar";

    try {
      $statu  = Statu::find($id);
      $statu->delete();
      $color = "success";
      $message = "Eliminado";
    } catch (\Throwable $th) {
      //throw $th;
    }
    return redirect()->route('status.index')->with(['message' => $message, 'color' => $color]);
  }
}

resources/views/admin/status/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-around">
    <div class="col-md-6 ">
      <h1>Editar dato</h1>
      <form action="{{route('status.update',$statu)}}" class="form-horizontal my-4" method="post">
        @csrf
        @method('PUT')
        <div class="form-group">
          <input type="text" class="form-control" value="{{old('name',$statu->name)}}" name="name" id="name"
            placeholder="Escriba el nombre">
        </div>
        <div class="form-group">
          <button class="btn btn-primary text-center btn-block">Guardar</button>
        </div>
      </form>
    </div>

  </div>
</div>

@endsection

resources/views/admin/status/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-around">
    <div class="col-md-4">
      <h1>Agregar dato</h1>
      <form action="{{route('status.store')}}" class="form-horizontal my-4" method="post">
        @csrf
        <div class="form-group">
          <input type="text" class="form-control" name="name" id="name" placeholder="Escriba el nombre">
        </div>
        <div class="form-group">
          <button class="btn btn-primary text-center btn-block">Guardar</button>
        </div>
      </form>
    </div>
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">{{ __('Estatus') }}</div>

        <div class="card-body">
          <table id="datatable" class="table table-responsive-sm table-striped">
            <thead>
              <tr>
                <th>Nombre</th>
                <th>Acciones</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              @foreach ($status as $s)
              <tr>
                <td>{{ $s->name }}</td>
                <td><a href="{{route('status.edit',$s)}}">Editar</a></td>
                <td>
                  <form action="{{route('status.destroy',$s)}}" method="post"
                    onclick="return confirm('¿Desea eliminar?'); return false;">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger">X</button>
                  </form>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>


        </div>
      </div>
    </div>
  </div>
</div>
@section('scripts')
<script src="{{URL::asset('js/datatable.js')}}"></script>
@endsection
@endsection