routes/web.php
<?php

use App\Http\Controllers\AreaController;
use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MarkController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\StatuController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect()->route('login');
});

Auth::routes();



Route::middleware(['auth'])->group(function () {
  Route::get('/home', [HomeController::class, 'index'])->name('home');
  Route::get('users', [UserController::class, 'index'])->name('users.index');
  Route::get('profile', [ProfileController::class, 'show'])->name('profile.show');
  Route::put('profile', [ProfileController::class, 'update'])->name('profile.update');
  Route::resource('areas', AreaController::class);
  Route::resource('categories', CategoryController::class);
  Route::resource('marks', MarkController::class);
  Route::resource('status', StatuController::class);
  Route::resource('products', ProductController::class);
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Product extends Model
{
  use HasFactory;
  protected $guarded = [];

  public function area(): BelongsTo
  {
    return $this->belongsTo(Area::class);
  }
  public function category(): BelongsTo
  {
    return $this->belongsTo(Category::class);
  }
  public function mark(): BelongsTo
  {
    return $this->belongsTo(Mark::class);
  }
  public function Statu(): BelongsTo
  {
    return $this->belongsTo(Statu::class);
  }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Product\AddRequest;
use App\Http\Requests\Product\UpdateRequest;
use App\Models\Area;
use App\Models\Category;
use App\Models\Mark;
use App\Models\Product;
use App\Models\Statu;
use Illuminate\Http\Request;

class ProductController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {

    $products = Product::all();
    return view('admin.products.index', compact('products'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    $categories = Category::all();
    $marks = Mark::all();
    $status = Statu::all();
    $areas = Area::all();
    return view('admin.products.add', compact(['categories', 'marks', 'status', 'areas']));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(AddRequest $request)
  {
    Product::create($request->all());
    return redirect()->route('products.index')->with(['message' => 'Agregado', 'color' => 'success']);
  }

  /**
   * Display the specified resource.
   *
   * @param  \App\Models\Product  $product
   * @return \Illuminate\Http\Response
   */
  public function show(Product $product)
  {
    //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  \App\Models\Product  $product
   * @return \Illuminate\Http\Response
   */
  public function edit(Product $product)
  {
    $categories = Category::all();
    $marks = Mark::all();
    $status = Statu::all();
    $areas = Area::all();
    return view('admin.products.edit', compact(['categories', 'marks', 'status', 'areas', 'product']));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  \App\Models\Product  $product
   * @return \Illuminate\Http\Response
   */
  public function update(UpdateRequest $request, Product $product)
  {
    Product::where('id', $product->id)->update($request->except(['_token', '_method']));
    return redirect()->route('products.index')->with(['message' => 'Editado', 'color' => 'success']);
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  \App\Models\Product  $product
   * @return \Illuminate\Http\Response
   */
  public function destroy(Product $product)
  {
    $color = "danger";
    $message = "No se pudo eliminar";

    try {
      $product->delete();
      $color = "success";
      $message = "Eliminado";
    } catch (\Throwable $th) {
      //throw $th;
    }
    return redirect()->route('products.index')->with(['message' => $message, 'color' => $color]);
  }
}

resources/views/admin/products/add.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-around">
    <div class="col-md-12 ">
      <h1>Agregar dato</h1>
      <form action="{{route('products.store')}}" class="form-horizontal my-4" method="post">
        @csrf
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <input type="text" class="form-control" value="{{old('name')}}" name="name" id="name"
                placeholder="Escriba el nombre">
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <input type="text" class="form-control" value="{{old('description')}}" name="description" id="description"
                placeholder="Escriba la descripcion">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <input type="number" class="form-control" value="{{old('count')}}" name="count" id="count"
                placeholder="Escribe la cantidad">
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <select name="category_id" id="category_id" class="form-control">
                <option value="" disabled selected>Selecciona la categoria</option>
                @forelse ($categories as $c)
                <option value="{{$c->id}}">{{$c->name}}</option>
                @empty
                <option value="" disabled>No hay categorias</option>
                @endforelse
              </select>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <select name="mark_id" id="mark_id" class="form-control">
                <option value="" disabled selected>Selecciona la marca</option>
                @forelse ($marks as $m)
                <option value="{{$m->id}}">{{$m->name}}</option>
                @empty
                <option value="" disabled>No hay marcas</option>
                @endforelse
              </select>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <select name="statu_id" id="statu_id" class="form-control">
                <option value="" disabled selected>Selecciona el estatus </option>
                @forelse ($status as $s)
                <option value="{{$s->id}}">{{$s->name}}</option>
                @empty
                <option value="" disabled>No hay status</option>
                @endforelse
              </select>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <select name="area_id" id="area_id" class="form-control">
                <option value="" disabled selected>Selecciona el area </option>
                @forelse ($areas as $a)
                <option value="{{$a->id}}">{{$a->name}}</option>
                @empty
                <option value="" disabled>No hay areas</option>
                @endforelse
              </select>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <button class="btn btn-primary text-center btn-block">Guardar</button>
            </div>
          </div>
        </div>
      </form>
    </div>

  </div>
</div>
@endsection

resources/views/admin/products/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-around">
    <div class="col-md-12 ">
      <h1>Editar dato</h1>
      <form action="{{route('products.update',$product)}}" class="form-horizontal my-4" method="post">
        @csrf
        @method('PUT')
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <input type="text" class="form-control" value="{{old('name',$product->name)}}" name="name" id="name"
                placeholder="Escriba el nombre">
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <input type="text" class="form-control" value="{{old('description',$product->description)}}"
                name="description" id="description" placeholder="Escriba la descripcion">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <input type="number" class="form-control" value="{{old('count',$product->count)}}" name="count" id="count"
                placeholder="Escribe la cantidad">
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <select name="category_id" id="category_id" class="form-control">
                <option value="" disabled selected>Selecciona la categoria</option>
                @forelse ($categories as $c)
                <option @if ( $product->category_id == $c->id) selected : @endif value="{{$c->id}}">{{$c->name}}
                </option>
                @empty
                <option value="" disabled>No hay categorias</option>
                @endforelse
              </select>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <select name="mark_id" id="mark_id" class="form-control">
                <option value="" disabled selected>Selecciona la marca</option>
                @forelse ($marks as $m)
                <option @if ( $product->mark_id == $m->id) selected : @endif value="{{$m->id}}">{{$m->name}}</option>
                @empty
                <option value="" disabled>No hay marcas</option>
                @endforelse
              </select>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <select name="statu_id" id="statu_id" class="form-control">
                <option value="" disabled selected>Selecciona el estatus </option>
                @forelse ($status as $s)
                <option @if ( $product->statu_id == $s->id) selected : @endif value="{{$s->id}}">{{$s->name}}</option>
                @empty
                <option value="" disabled>No hay status</option>
                @endforelse
              </select>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <select name="area_id" id="area_id" class="form-control">
                <option value="" disabled selected>Selecciona el area </option>
                @forelse ($areas as $a)
                <option @if ( $product->area_id == $a->id) selected : @endif value="{{$a->id}}">{{$a->name}}</option>
                @empty
                <option value="" disabled>No hay areas</option>
                @endforelse
              </select>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <button class="btn btn-primary text-center btn-block">Guardar</button>
            </div>
          </div>
        </div>
      </form>
    </div>

  </div>
</div>
@endsection

resources/views/admin/products/index.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-12">
  <div class="card">
    <div class="card-header">
      <div class="row">
        <h4 class="text-primary mx-auto">{{ __('Productos') }}</h4>
        <a href="{{route('products.create')}}" class="btn btn-primary mx-auto">Agregar</a>
      </div>
    </div>

    <div class="card-body">
      <table id="datatable" class="table table-responsive-sm table-striped">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Cantidad</th>
            <th>Area</th>
            <th>Marca</th>
            <th>Categorias</th>
            <th>Ultima modificación</th>
            <th>Estado</th>
            <th>Acciones</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          @foreach ($products as $p)
          <tr>
            <td>{{ $p->name }}</td>
            <td>{{ $p->description }}</td>
            <td>{{ $p->count }}</td>
            <td>{{ $p->area->name }}</td>
            <td>{{ $p->mark->name }}</td>
            <td>{{ $p->category->name }}</td>
            <td>{{ $p->updated_at}}</td>
            <td>{{ $p->statu->name }}</td>
            <td><a href="{{route('products.edit',$p)}}">Editar</a></td>
            <td>
              <form action="{{route('products.destroy',$p)}}" method="post"
                onclick="return confirm('¿Desea eliminar?'); return false;">
                @csrf
                @method('DELETE')
                <button class="btn btn-danger">X</button>
              </form>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>

    </div>
  </div>
</div>

@section('scripts')
<script src="{{URL::asset('js/datatable.js')}}"></script>
@endsection
@endsection